ERROR_FILE_NOT_FOUND = -2;
ERROR_PATH_NOT_FOUND = -3;
ERROR_ACCESS_DENIED = -5;
ERROR_SHARING_VIOLATION = -32;
ERROR_INVALID_NAME = -123;
ERROR_FILE_EXISTS = -80;
ERROR_ALREADY_EXISTS = -183;

DOKAN_SUCCESS = 0;
DOKAN_ERROR = -1; #General Error
DOKAN_DRIVE_LETTER_ERROR = -2; #Bad Drive letter
DOKAN_DRIVER_INSTALL_ERROR = -3; #Can't install driver
DOKAN_START_ERROR = -4; #Driver something wrong
DOKAN_MOUNT_ERROR = -5; #Can't assign drive letter

FILE_ACCESS_READ = 1
FILE_ACCESS_WRITE = 2

FILE_SHARE_NONE = 0
FILE_SHARE_READ = 1
FILE_SHARE_WRITE = 2
FILE_SHARE_DELETE = 4

FILE_MODE_CREATENEW = 1
FILE_MODE_CREATE = 2
FILE_MODE_OPEN = 3
FILE_MODE_OPENORCREATE = 4
FILE_MODE_TRUNCATE = 5
FILE_MODE_APPEND = 6
FILE_MODE = [ FILE_MODE_CREATENEW, FILE_MODE_CREATE, FILE_MODE_OPEN, FILE_MODE_OPENORCREATE, FILE_MODE_TRUNCATE, FILE_MODE_APPEND ]

FILE_OPTIONS_WRITETHROUGH = -2147483648
FILE_OPTIONS_NONE = 0
FILE_OPTIONS_ENCRYPTED = 16384
FILE_OPTIONS_DELETEONCLOSE = 67108864
FILE_OPTIONS_SEQUENTIALSCAN = 134217728
FILE_OPTIONS_RANDOMACCESS = 268435456
FILE_OPTIONS_ASYNCHRONOUS = 1073741824
FILE_OPTIONS = [ FILE_OPTIONS_WRITETHROUGH, FILE_OPTIONS_NONE, FILE_OPTIONS_ENCRYPTED, FILE_OPTIONS_DELETEONCLOSE, FILE_OPTIONS_SEQUENTIALSCAN, FILE_OPTIONS_RANDOMACCESS, FILE_OPTIONS_ASYNCHRONOUS ]