ERROR_FILE_NOT_FOUND = 2;
ERROR_PATH_NOT_FOUND = 3;
ERROR_ACCESS_DENIED = 5;
ERROR_SHARING_VIOLATION = 32;
ERROR_INVALID_NAME = 123;
ERROR_FILE_EXISTS = 80;
ERROR_ALREADY_EXISTS = 183;

DOKAN_SUCCESS = 0;
DOKAN_ERROR = -1; #General Error
DOKAN_DRIVE_LETTER_ERROR = -2; #Bad Drive letter
DOKAN_DRIVER_INSTALL_ERROR = -3; #Can't install driver
DOKAN_START_ERROR = -4; #Driver something wrong
DOKAN_MOUNT_ERROR = -5; #Can't assign drive letter